apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
  namespace: default
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
        labels:
          app: api
    spec:
      containers:
        - name: image
          image: 418590747430.dkr.ecr.us-west-2.amazonaws.com/udacity:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: api
  type: LoadBalancer
