Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  EKSARNRole:
    Description: EKS ARN Role
    Type: String

Resources:
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http to our load balancer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID" 
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  KubernetesSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID" 
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress: 
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  KubernetesCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: KubernetesCluster
      ResourcesVpcConfig:
        SecurityGroupIds: 
          - !Ref 'KubernetesSecGroup'
        SubnetIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}-PRI1-SN
          - Fn::ImportValue: !Sub ${EnvironmentName}-PRI2-SN
      RoleArn: !Sub ${EKSARNRole}

